added if loops to check if it is a Staging or Production deployment request

diff --git a/.github/workflows/build-deploy-apps-staging-CLI.yml b/.github/workflows/build-deploy-apps-staging-CLI.yml
--- a/.github/workflows/build-deploy-apps-staging-CLI.yml
+++ b/.github/workflows/build-deploy-apps-staging-CLI.yml
@@ -592,18 +592,34 @@ jobs:
         API_GATEWAY_LIVENESS_PROBE_CFG="spring-petclinic-${{ env.API_GATEWAY }}/${{ env.DEPLOYMENT_LIVENESS_PROBE_CFG }}"
         API_GATEWAY_READINESS_PROBE_CFG="spring-petclinic-${{ env.API_GATEWAY }}/${{ env.DEPLOYMENT_READINESS_PROBE_CFG }}"
         
+        if [ $DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "deploy" ]
+        then
+          echo "Set deployment name to STAGING"
+          DEPLOYMENT_NAME=${{ steps.set-var.outputs.VETS_SERVICE_STAGING_DEPLOYMENT }}
+        else
+          if [ !$DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "set-production" ]
+          then
+              echo "Set deployment name to PRODUCTION"
+              DEPLOYMENT_NAME=${{ steps.set-var.outputs.VETS_SERVICE_PRODUCTION_DEPLOYMENT }}
+          else
+              echo "ERROR Input param DEPLOYMENT_STAGING and DEPLOYMENT_ACTION are NOT consistent, choose [DEPLOYMENT_STAGING=true with DEPLOYMENT_ACTION=deploy for Staging] OR [DEPLOYMENT_STAGING=false with DEPLOYMENT_ACTION=set-production for Go Live]"
+              exit 1
+          fi
+        fi
+        echo "DEPLOYMENT_NAME="$DEPLOYMENT_NAME
+
         echo "Cheking if any deployment already exist ..."
         vets_deployment=$(az spring app deployment list --app  ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }})
 
         if [[ $(echo $vets_deployment | jq -r 'length') -eq 0 ]]
         then
-            echo "There is no existing deployment for XXX"
+            echo "There is no existing deployment for vets-service"
             if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
             then
-              echo "About to create a new Staging Deployment for XXX"
+              echo "About to create a new Deployment for vets-service"
 
               az spring app deployment create \
-              --name  ${{ needs.build.outputs.VETS_SERVICE_DEPLOYMENT }} \
+              --name $DEPLOYMENT_NAME \
               --app ${{ env.VETS_SERVICE }} \
               --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
               --instance-count ${{ env.DEPLOYMENT_INSTANCE_COUNT }} \
@@ -625,53 +641,49 @@ jobs:
             fi
    
         else
-            echo "There are existing deployment(s) for XXX"
+            echo "There are existing deployment(s) for vets-service"
+            for deployment in $(az spring app deployment list --app ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
+            do
+              echo "About to check Deployment " $deployment
+              az spring app deployment show --name $deployment --app ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            done
         fi
 
-        for deployment in $(az spring app deployment list --app ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
-        do
-          echo "About to check Deployment " $deployment
-          az spring app deployment show --name $deployment --app ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
-        done
-
-
-        echo "In az spring app deploy ,  --deployment is the Name of an existing deployment of the app. Default to the production"
+        echo "In az spring app deploy , --deployment is the Name of an existing deployment of the app. Default to the production"
 
         if [ $DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "deploy" ]
         then
-            echo "About to deploy XXX to a Staging environment"
+            echo "About to deploy vets-service to a Staging environment"
+            az spring app deploy \
+            --name  ${{ env.VETS_SERVICE }} \
+            --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
+            --artifact-path ${{ needs.build.outputs.VETS_SERVICE_PACKAGE_PATH }} \
+            --deployment ${{ steps.set-var.outputs.VETS_SERVICE_STAGING_DEPLOYMENT }} \
+            --disable-probe ${{ env.DEPLOYMENT_DISABLE_PROBE }} \
+            --enable-startup-probe ${{ env.DEPLOYMENT_ENABLE_STARTUP_PROBE }} \
+            --enable-liveness-probe ${{ env.DEPLOYMENT_ENABLE_LIVENESS_PROBE }} \
+            --enable-readiness-probe ${{ env.DEPLOYMENT_ENABLE_READINESS_PROBE }} \
+            --startup-probe-config $VETS_SERVICE_STARTUP_PROBE_CFG \
+            --liveness-probe-config $VETS_SERVICE_LIVENESS_PROBE_CFG \
+            --readiness-probe-config $VETS_SERVICE_READINESS_PROBE_CFG \
+            --termination-grace-period-seconds ${{ env.GRACE_PERIOD }} \
+            --env "-SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT ${{ env.SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT }} -VETS_SVC_APP_IDENTITY_CLIENT_ID ${{ env.VETS_SVC_APP_IDENTITY_CLIENT_ID }} -SPRING_CLOUD_AZURE_TENANT_ID ${{ env.SPRING_CLOUD_AZURE_TENANT_ID }}" \
+            --jvm-options ${{ env.DEPLOYMENT_JVM_OPTIONS }} \
+            --version ${{ env.DEPLOYMENT_VERSION }} \
+            --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \            
         else
           if [ !$DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "set-production" ]
           then
-              echo "About to Set Production deployment of XXX App ..."
-              az spring app set-deployment -d  ${{ steps.set-var.outputs.VETS_SERVICE_PRODUCTION_DEPLOYMENT }} -n ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+              echo "About to Set Production deployment of vets-service App ..."
+              az spring app set-deployment -d ${{ steps.set-var.outputs.VETS_SERVICE_PRODUCTION_DEPLOYMENT }} -n ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
           else
               echo "ERROR Input param DEPLOYMENT_STAGING and DEPLOYMENT_ACTION are NOT consistent, choose [DEPLOYMENT_STAGING=true with DEPLOYMENT_ACTION=deploy for Staging] OR [DEPLOYMENT_STAGING=false with DEPLOYMENT_ACTION=set-production for Go Live]"
               exit 1
           fi
         fi
 
-        echo "About to deploy vets-service ... "
-        az spring app deploy \
-        --name  ${{ env.VETS_SERVICE }} \
-        --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
-        --artifact-path ${{ needs.build.outputs.VETS_SERVICE_PACKAGE_PATH }} \
-        --deployment ${{ needs.build.outputs.VETS_SERVICE_DEPLOYMENT }} \
-        --disable-probe ${{ env.DEPLOYMENT_DISABLE_PROBE }} \
-        --enable-startup-probe ${{ env.DEPLOYMENT_ENABLE_STARTUP_PROBE }} \
-        --enable-liveness-probe ${{ env.DEPLOYMENT_ENABLE_LIVENESS_PROBE }} \
-        --enable-readiness-probe ${{ env.DEPLOYMENT_ENABLE_READINESS_PROBE }} \
-        --startup-probe-config $VETS_SERVICE_STARTUP_PROBE_CFG \
-        --liveness-probe-config $VETS_SERVICE_LIVENESS_PROBE_CFG \
-        --readiness-probe-config $VETS_SERVICE_READINESS_PROBE_CFG \
-        --termination-grace-period-seconds ${{ env.GRACE_PERIOD }} \
-        --env "-SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT ${{ env.SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT }} -VETS_SVC_APP_IDENTITY_CLIENT_ID ${{ env.VETS_SVC_APP_IDENTITY_CLIENT_ID }} -SPRING_CLOUD_AZURE_TENANT_ID ${{ env.SPRING_CLOUD_AZURE_TENANT_ID }}" \
-        --jvm-options ${{ env.DEPLOYMENT_JVM_OPTIONS }} \
-        --version ${{ env.DEPLOYMENT_VERSION }} \
-        --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
-
         echo "About to assign endpoint to vets-service ... "
-        az spring app update --name  ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} --assign-endpoint true
+        az spring app update --name ${{ env.VETS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} --assign-endpoint true
 
         echo "****************************************************************************************"
         echo "*                                                                                      *"
