check if Prod deployment already exist

diff --git a/.github/workflows/build-deploy-ui-staging-CLI.yml b/.github/workflows/build-deploy-ui-staging-CLI.yml
--- a/.github/workflows/build-deploy-ui-staging-CLI.yml
+++ b/.github/workflows/build-deploy-ui-staging-CLI.yml
@@ -100,7 +100,7 @@ on: # [push]
   workflow_dispatch:
     
 jobs:
-  build:
+  deploy-apps:
     outputs:
       API_GATEWAY_JAR_ARTIFACT: ${{ steps.set-var.outputs.API_GATEWAY_JAR_ARTIFACT }}
       API_GATEWAY_PACKAGE_PATH: ${{ steps.set-var2.outputs.API_GATEWAY_PACKAGE_PATH }}
@@ -170,80 +170,45 @@ jobs:
 
       shell: bash
 
-    # Something to note, actions/checkout@v2 no longer sets the github workspace to the path input, which means you may need to manually set the working directory for your runs step
-    # https://github.com/actions/checkout/blob/main/adrs/0153-checkout-v2.md#path
-        
-    - name: Checkout your repo
-      uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout
-      
-    - name: Set up JDK 11
-      uses: actions/setup-java@v2
-      with:
-        java-version: '11'
-        distribution: 'microsoft'
-        cache: maven
-  
-    - name: Build with Maven
-      id: mvn_build
-      run: | 
-        echo "****************************************************************************************"
-        echo "*                                                                                      *"
-        echo "*                                                                                      *"
-        echo "* /!\ IMPORTANT WARNING: projects must be built with -Denv=cloud                       *"
-        echo "* EXCEPT for api-gateway                                                               *"
-        echo "*                                                                                      *"
-        echo "*                                                                                      *"
-        echo "****************************************************************************************"
-              
-        mvn -B clean package --file pom.xml -DskipTests
-        
-        echo "github.workspace = ${{ github.workspace }}"
-        pwd
-
-        echo "****************************************************************************************"
-        echo "*                                                                                      *"
-        echo "*                                                                                      *"
-        echo "*Checking Artifacts ...                                                                *"
-        echo "*                                                                                      *"
-        echo "*                                                                                      *"
-        echo "****************************************************************************************"
-
-        ls -al
-        echo ""
-        echo ""
-
-        ls -al spring-petclinic-api-gateway/target/*.jar
-
-    - name: Archive API-GATEWAY Jar artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: ${{ env.API_GATEWAY }}
-        path: ${{ github.workspace }}/${{ env.API_GATEWAY_JAR }}
-        retention-days: 5
-
-    - name: Authorize local IP access to the Azure BLOB Storage 
-      if: ${{ always() }}
-      run: |
-        echo "About to ADD network-rule to ALLOW $LOCAL_IP to Azure BLOB Storage ${{ env.AZ_STORAGE_NAME }}"
-        az storage account network-rule add --ip-address $LOCAL_IP --account-name  ${{ env.AZ_STORAGE_NAME }}  --action "Allow" -g ${{ env.RG_APP }}  --only-show-errors
-        sleep 30        
-      shell: bash
-
-    - name: Upload Artifacts to Azure BLOB Storage
-      id: blob_upload
+    - name: Download Artifacts from Azure BLOB Storage
+      id: blob_download
       run: | 
         # https://learn.microsoft.com/en-us/azure/storage/blobs/blob-cli
 
         # Runner will be blocked by network rules of storage account. Must Allow its IP
         # TODO in Bicep : RBAC ==> GH Runner SPN must have "Storage Blob Data Contributor" Role on the storage Account
 
-        echo "About to upload Artifcats to Azure BLOB Storage. /!\ --overwrite' is in preview and under development"
-        echo "AZ_BLOB_MAX_CONNECTIONS=${{ env.AZ_BLOB_MAX_CONNECTIONS }}"
-        echo "AZ_BLOB_TIMEOUT=${{ env.AZ_BLOB_TIMEOUT }} "
-        echo "AZ_BLOB_MAX_CONNECTIONS=${{ env.AZ_BLOB_MAX_CONNECTIONS }}"
+        pwd
+        ls -al
 
-        # https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations
-        az storage blob upload --name ${{ env.API_GATEWAY }} --file ${{ github.workspace }}/${{ env.API_GATEWAY_JAR }} --container-name ${{ env.AZ_BLOB_CONTAINER_NAME }} --account-name ${{ env.AZ_STORAGE_NAME }} --auth-mode login --overwrite --max-connections ${{ env.AZ_BLOB_MAX_CONNECTIONS }} --timeout ${{ env.AZ_BLOB_TIMEOUT }}
+        mkdir ${{ github.workspace }}/${{ env.VETS_SERVICE }}
+        mkdir ${{ github.workspace }}/${{ env.VISITS_SERVICE }}
+        mkdir ${{ github.workspace }}/${{ env.CUSTOMERS_SERVICE }}
+        mkdir ${{ github.workspace }}/${{ env.API_GATEWAY }}
+
+        ls -al ${{ github.workspace }}/${{ env.VETS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.VISITS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.CUSTOMERS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.API_GATEWAY }}
+
+        echo "VETS_SERVICE_PACKAGE_PATH=${{ env.VETS_SERVICE_PACKAGE_PATH }}"
+        echo "VISITS_SERVICE_PACKAGE_PATH=${{ env.VISITS_SERVICE_PACKAGE_PATH }}"
+        echo "CUSTOMERS_SERVICE_PACKAGE_PATH=${{ env.CUSTOMERS_SERVICE_PACKAGE_PATH }}"
+        echo "API_GATEWAY_PACKAGE_PATH=${{ env.API_GATEWAY_PACKAGE_PATH }}"
+
+        echo "About to download Artifcats from Azure BLOB Storage"
+        # --blob-url  ? https://stasapetcliasa.blob.core.windows.net/petcliasa-blob/asa-spring-petclinic-admin-server-2.6.6.jar
+        az storage blob download --name ${{ env.VETS_SERVICE }} --file $VETS_SERVICE_PACKAGE_PATH --container-name ${{ env.AZ_BLOB_CONTAINER_NAME }} --account-name ${{ env.AZ_STORAGE_NAME }} --auth-mode login --max-connections ${{ env.AZ_BLOB_MAX_CONNECTIONS }}
+        az storage blob download --name ${{ env.CUSTOMERS_SERVICE }} --file $CUSTOMERS_SERVICE_PACKAGE_PATH --container-name ${{ env.AZ_BLOB_CONTAINER_NAME }} --account-name ${{ env.AZ_STORAGE_NAME }} --auth-mode login --max-connections ${{ env.AZ_BLOB_MAX_CONNECTIONS }}
+        az storage blob download --name ${{ env.VISITS_SERVICE }} --file $VISITS_SERVICE_PACKAGE_PATH --container-name ${{ env.AZ_BLOB_CONTAINER_NAME }} --account-name ${{ env.AZ_STORAGE_NAME }} --auth-mode login --max-connections ${{ env.AZ_BLOB_MAX_CONNECTIONS }}
+        az storage blob download --name ${{ env.API_GATEWAY }} --file $API_GATEWAY_PACKAGE_PATH --container-name ${{ env.AZ_BLOB_CONTAINER_NAME }} --account-name ${{ env.AZ_STORAGE_NAME }} --auth-mode login --max-connections ${{ env.AZ_BLOB_MAX_CONNECTIONS }}
+
+        ls -al ${{ github.workspace }}/${{ env.VETS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.VISITS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.CUSTOMERS_SERVICE }}
+        ls -al ${{ github.workspace }}/${{ env.API_GATEWAY }}
+
+      shell: bash
 
     - name: Disable local IP access to the Azure BLOB Storage 
       if: ${{ always() }}
@@ -251,23 +216,6 @@ jobs:
         echo "About to REMOVE network-rule ALLOWING $LOCAL_IP to Azure BLOB Storage ${{ env.AZ_STORAGE_NAME }}"
         az storage account network-rule remove --ip-address $LOCAL_IP --account-name  ${{ env.AZ_STORAGE_NAME }} -g ${{ env.RG_APP }} --only-show-errors
       shell: bash
-
-  deploy-apps:
-    needs: [build]
-    runs-on: ubuntu-latest # [self-hosted, linux, x64]
-    steps: 
-
-    - name: Azure Login
-      uses: azure/login@v1.4.6 # https://github.com/marketplace/actions/azure-login
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-
-    - name: Checkout your repo
-      uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout
-
-    # You can  download all artifacts in a workflow run by not specifying a name.
-    - name: Download ALL Jar artifacts
-      uses: actions/download-artifact@v3
 
     - name: Check Artifacts
       run: | 
@@ -280,8 +228,9 @@ jobs:
         ls -al ${{ env.GH_WORKSPACE }}
         echo ""
 
-        echo "API_GATEWAY_PACKAGE_PATH=${{ github.workspace }}/${{ env.API_GATEWAY }}/${{ needs.build.outputs.API_GATEWAY_JAR_ARTIFACT }}"
+        echo "API_GATEWAY_PACKAGE_PATH=${{ env.API_GATEWAY_PACKAGE_PATH }}"
 
+      
         echo "****************************************************************************************"
         echo "*                                                                                      *"
         echo "*                                                                                      *"
@@ -290,33 +239,29 @@ jobs:
         echo "*                                                                                      *"
         echo "****************************************************************************************"
 
-        echo "API_GATEWAY_PACKAGE_PATH=${{ needs.build.outputs.API_GATEWAY_PACKAGE_PATH }}"
+        echo "API_GATEWAY_PACKAGE_PATH=${{ env.API_GATEWAY_PACKAGE_PATH }}"
 
         echo ""
         ls -al ${{ env.API_GATEWAY }}
         echo ""
-        ls -al ${{ needs.build.outputs.API_GATEWAY_PACKAGE_PATH }} # ${{ env.API_GATEWAY_PACKAGE_PATH }}           
+        ls -al ${{ env.API_GATEWAY_PACKAGE_PATH }}           
         echo ""
 
-        echo ""
-        echo "API_GATEWAY_STAGING_DEPLOYMENT=${{ needs.build.outputs.API_GATEWAY_STAGING_DEPLOYMENT }}"
-        echo ""
 
-        echo ""
-        echo "API_GATEWAY_PRODUCTION_DEPLOYMENT=${{ needs.build.outputs.API_GATEWAY_PRODUCTION_DEPLOYMENT }}"
-        echo ""
+    - name: Deploy UI
+      run: | 
 
-        echo ""
-        echo "KV URI=${{ env.SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT }}"
-        echo "TENANT=${{ env.SPRING_CLOUD_AZURE_TENANT_ID }}"
-        echo ""
-        
         az config set extension.use_dynamic_install=yes_without_prompt
         az extension add --name spring
         az extension update --name spring
 
-    - name: Deploy UI
-      run: | 
+        echo ""
+        echo "API_GATEWAY_STAGING_DEPLOYMENT=${{ env.API_GATEWAY_STAGING_DEPLOYMENT }}"
+        echo ""
+
+        echo ""
+        echo "API_GATEWAY_PRODUCTION_DEPLOYMENT=${{ env.API_GATEWAY_PRODUCTION_DEPLOYMENT }}"
+        echo ""
 
         echo "****************************************************************************************"
         echo "*                                                                                      *"
@@ -337,12 +282,12 @@ jobs:
         if [ $DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "deploy" ]
         then
           echo "Set deployment name to STAGING"
-          DEPLOYMENT_NAME=${{ needs.build.outputs.API_GATEWAY_STAGING_DEPLOYMENT }}
+          DEPLOYMENT_NAME=${{ env.API_GATEWAY_STAGING_DEPLOYMENT }}
         else
           if [ !$DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "set-production" ]
           then
               echo "Set deployment name to PRODUCTION"
-              DEPLOYMENT_NAME=${{ needs.build.outputs.API_GATEWAY_PRODUCTION_DEPLOYMENT }}
+              DEPLOYMENT_NAME=${{ env.API_GATEWAY_PRODUCTION_DEPLOYMENT }}
           else
               echo "ERROR Input param DEPLOYMENT_STAGING and DEPLOYMENT_ACTION are NOT consistent, choose [DEPLOYMENT_STAGING=true with DEPLOYMENT_ACTION=deploy for Staging] OR [DEPLOYMENT_STAGING=false with DEPLOYMENT_ACTION=set-production for Go Live]"
               exit 1
@@ -356,24 +301,6 @@ jobs:
         if [[ $(echo $apigw_deployment | jq -r 'length') -eq 0 ]]
         then
             echo "There is no existing deployment for ${{ env.API_GATEWAY }}"
-        else
-            echo "There are existing deployment(s) for ${{ env.API_GATEWAY }}"
-            for deployment in $(az spring app deployment list --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
-            do
-              echo "About to check Deployment " $deployment
-              az spring app deployment show --name $deployment --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
-            done
-        fi
-
-        # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed
-        # check if THIS $DEPLOYMENT_NAME already exists
-  
-        trap 'catch $? $LINENO' ERR
-        catch() {
-          echo "Error $1 occurred on $2"
-          echo "Deployment $DEPLOYMENT_NAME NOT found"
-          if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
-          then
             echo "About to create a new Deployment $DEPLOYMENT_NAME"
             
             az spring app deployment create \
@@ -385,20 +312,55 @@ jobs:
             --memory ${{ env.DEPLOYMENT_MEMORY }} \
             --version ${{ env.DEPLOYMENT_VERSION }} \
             --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
-            --skip-clone-settings
-          else
-            echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
-            exit 1
-          fi
-        }
-        echo "check if $DEPLOYMENT_NAME deployment already exists ... "
-        az spring app deployment show --name $DEPLOYMENT_NAME --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            --skip-clone-settings            
+        else
+            echo "There are existing deployment(s) for ${{ env.API_GATEWAY }}"
+            FOUND_DEPLOYMENT=false
+            for deployment in $(az spring app deployment list --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
+            do
+              echo "About to check Deployment " $deployment
+              if [[ $deployment == $DEPLOYMENT_NAME ]]
+              then
+                echo $DEPLOYMENT_NAME deployment already exists
+                FOUND_DEPLOYMENT=true
+              fi
+            done
+            if [[ $FOUND_DEPLOYMENT == true ]]
+            then
+                az spring app deployment show --name $deployment --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            else
+              # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed  
+              trap 'catch $? $LINENO' ERR
+              catch() {
+                echo "Error $1 occurred on $2"
+              }
+              echo "Deployment $DEPLOYMENT_NAME NOT found among the existing deployments"
+              if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
+              then
+                echo "About to create a new Deployment $DEPLOYMENT_NAME"
+                
+                az spring app deployment create \
+                --name $DEPLOYMENT_NAME \
+                --app ${{ env.API_GATEWAY }} \
+                --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
+                --instance-count ${{ env.DEPLOYMENT_INSTANCE_COUNT }} \
+                --cpu ${{ env.DEPLOYMENT_CPU }} \
+                --memory ${{ env.DEPLOYMENT_MEMORY }} \
+                --version ${{ env.DEPLOYMENT_VERSION }} \
+                --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
+                --skip-clone-settings
+              else
+                echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
+                exit 1
+              fi              
+            fi
+        fi
 
         echo "About to deploy App ..."
         az spring app deploy \
         --name ${{ env.API_GATEWAY }} \
         --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
-        --artifact-path ${{ needs.build.outputs.API_GATEWAY_PACKAGE_PATH }} \
+        --artifact-path ${{ env.API_GATEWAY_PACKAGE_PATH }} \
         --deployment $DEPLOYMENT_NAME \
         --disable-probe true \
         --jvm-options="${{ env.DEPLOYMENT_JVM_OPTIONS }}" \
@@ -412,6 +374,17 @@ jobs:
           if [ !$DEPLOYMENT_STAGING ] && [ $DEPLOYMENT_ACTION == "set-production" ]
           then
               echo "About to Set $DEPLOYMENT_NAME as Production deployment ..."
+              # https://github.com/Azure/Azure-Spring-Apps/issues/17
+              # [].properties.active = true mean it is a Production Deployment
+              prod_deployment_active=$(az spring app deployment show --name $DEPLOYMENT_NAME --app ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].properties.active')
+              echo "Checking if $DEPLOYMENT_NAME is alreasdy set to Active/Production:" $prod_deployment_active
+              if [ $prod_deployment_active ]
+              then
+                echo "$DEPLOYMENT_NAME is already set to Production"
+              else
+                echo "About to set $DEPLOYMENT_NAME to Production"
+                az spring app set-deployment -d $DEPLOYMENT_NAME -n ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+
               az spring app set-deployment -d $DEPLOYMENT_NAME -n ${{ env.API_GATEWAY }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
           else
               echo "ERROR Input param DEPLOYMENT_STAGING and DEPLOYMENT_ACTION are NOT consistent, choose [DEPLOYMENT_STAGING=true with DEPLOYMENT_ACTION=deploy for Staging] OR [DEPLOYMENT_STAGING=false with DEPLOYMENT_ACTION=set-production for Go Live]"
