corrected Visists & Customers deployments

diff --git a/.github/workflows/build-deploy-apps-staging-CLI.yml b/.github/workflows/build-deploy-apps-staging-CLI.yml
--- a/.github/workflows/build-deploy-apps-staging-CLI.yml
+++ b/.github/workflows/build-deploy-apps-staging-CLI.yml
@@ -504,7 +504,7 @@ jobs:
                 exit 1
               fi              
             fi
-          fi
+        fi
 
         echo "About to deploy App ..."
         az spring app deploy \
@@ -576,24 +576,6 @@ jobs:
         if [[ $(echo $vets_deployment | jq -r 'length') -eq 0 ]]
         then
             echo "There is no existing deployment for ${{ env.VISITS_SERVICE }}"
-        else
-            echo "There are existing deployment(s) for ${{ env.VISITS_SERVICE }}"
-            for deployment in $(az spring app deployment list --app ${{ env.VISITS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
-            do
-              echo "About to check Deployment " $deployment
-              az spring app deployment show --name $deployment --app ${{ env.VISITS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
-            done
-        fi
-
-        # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed
-        # check if THIS $DEPLOYMENT_NAME already exists
-  
-        trap 'catch $? $LINENO' ERR
-        catch() {
-          echo "Error $1 occurred on $2"
-          echo "Deployment $DEPLOYMENT_NAME NOT found"
-          if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
-          then
             echo "About to create a new Deployment $DEPLOYMENT_NAME"
             
             az spring app deployment create \
@@ -605,14 +587,49 @@ jobs:
             --memory ${{ env.DEPLOYMENT_MEMORY }} \
             --version ${{ env.DEPLOYMENT_VERSION }} \
             --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
-            --skip-clone-settings
-          else
-            echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
-            exit 1
-          fi
-        }
-        echo "check if $DEPLOYMENT_NAME deployment already exists ... "
-        az spring app deployment show --name $DEPLOYMENT_NAME --app ${{ env.VISITS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            --skip-clone-settings               
+        else
+            echo "There are existing deployment(s) for ${{ env.VISITS_SERVICE }}"
+            FOUND_DEPLOYMENT=false
+            for deployment in $(az spring app deployment list --app ${{ env.VISITS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
+            do
+              echo "About to check Deployment " $deployment
+              if [[ $deployment == $DEPLOYMENT_NAME ]]
+              then
+                echo $DEPLOYMENT_NAME deployment already exists
+                FOUND_DEPLOYMENT=true
+              fi
+            done
+            if [[ $FOUND_DEPLOYMENT == true ]]
+            then
+                az spring app deployment show --name $deployment --app ${{ env.VISITS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            else
+              # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed  
+              trap 'catch $? $LINENO' ERR
+              catch() {
+                echo "Error $1 occurred on $2"
+              }
+              echo "Deployment $DEPLOYMENT_NAME NOT found among the existing deployments"
+              if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
+              then
+                echo "About to create a new Deployment $DEPLOYMENT_NAME"
+                
+                az spring app deployment create \
+                --name $DEPLOYMENT_NAME \
+                --app ${{ env.VISITS_SERVICE }} \
+                --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
+                --instance-count ${{ env.DEPLOYMENT_INSTANCE_COUNT }} \
+                --cpu ${{ env.DEPLOYMENT_CPU }} \
+                --memory ${{ env.DEPLOYMENT_MEMORY }} \
+                --version ${{ env.DEPLOYMENT_VERSION }} \
+                --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
+                --skip-clone-settings
+              else
+                echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
+                exit 1
+              fi              
+            fi        
+        fi
 
         echo "About to deploy App ..."
         az spring app deploy \
@@ -683,24 +700,6 @@ jobs:
         if [[ $(echo $vets_deployment | jq -r 'length') -eq 0 ]]
         then
             echo "There is no existing deployment for ${{ env.CUSTOMERS_SERVICE }}"
-        else
-            echo "There are existing deployment(s) for ${{ env.CUSTOMERS_SERVICE }}"
-            for deployment in $(az spring app deployment list --app ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
-            do
-              echo "About to check Deployment " $deployment
-              az spring app deployment show --name $deployment --app ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
-            done
-        fi
-
-        # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed
-        # check if THIS $DEPLOYMENT_NAME already exists
-  
-        trap 'catch $? $LINENO' ERR
-        catch() {
-          echo "Error $1 occurred on $2"
-          echo "Deployment $DEPLOYMENT_NAME NOT found"
-          if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
-          then
             echo "About to create a new Deployment $DEPLOYMENT_NAME"
             
             az spring app deployment create \
@@ -712,14 +711,50 @@ jobs:
             --memory ${{ env.DEPLOYMENT_MEMORY }} \
             --version ${{ env.DEPLOYMENT_VERSION }} \
             --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
-            --skip-clone-settings
-          else
-            echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
-            exit 1
-          fi
-        }
-        echo "check if $DEPLOYMENT_NAME deployment already exists ... "
-        az spring app deployment show --name $DEPLOYMENT_NAME --app ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            --skip-clone-settings            
+
+        else
+            echo "There are existing deployment(s) for ${{ env.CUSTOMERS_SERVICE }}"
+            FOUND_DEPLOYMENT=false
+            for deployment in $(az spring app deployment list --app ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} | jq -r '.[].name')
+            do
+              echo "About to check Deployment " $deployment
+              if [[ $deployment == $DEPLOYMENT_NAME ]]
+              then
+                echo $DEPLOYMENT_NAME deployment already exists
+                FOUND_DEPLOYMENT=true
+              fi
+            done
+            if [[ $FOUND_DEPLOYMENT == true ]]
+            then
+                az spring app deployment show --name $deployment --app ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
+            else
+              # https://unix.stackexchange.com/questions/22726/how-to-conditionally-do-something-if-a-command-succeeded-or-failed  
+              trap 'catch $? $LINENO' ERR
+              catch() {
+                echo "Error $1 occurred on $2"
+              }
+              echo "Deployment $DEPLOYMENT_NAME NOT found among the existing deployments"
+              if [[ ${{ env.DEPLOYMENT_CREATE_NEW }} ]]
+              then
+                echo "About to create a new Deployment $DEPLOYMENT_NAME"
+                
+                az spring app deployment create \
+                --name $DEPLOYMENT_NAME \
+                --app ${{ env.CUSTOMERS_SERVICE }} \
+                --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} \
+                --instance-count ${{ env.DEPLOYMENT_INSTANCE_COUNT }} \
+                --cpu ${{ env.DEPLOYMENT_CPU }} \
+                --memory ${{ env.DEPLOYMENT_MEMORY }} \
+                --version ${{ env.DEPLOYMENT_VERSION }} \
+                --runtime-version ${{ env.DEPLOYMENT_RUNTIME_VERSION }} \
+                --skip-clone-settings
+              else
+                echo "ERROR Input param DEPLOYMENT_CREATE_NEW is set to false, no new Deployment will be created"
+                exit 1
+              fi              
+            fi
+        fi
 
         echo "About to deploy App ..."
         az spring app deploy \
